spring:
  application:
    name: realworld-app
  liquibase:
    change-log: classpath:db/changelog-master.xml
  jpa:
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
  jackson:
    default-property-inclusion: non_null
    deserialization:
      unwrap-root-value: true
