server:
  port: 1748

spring:
  datasource:
    password: ${DB_PASSWORD:postgres}
    username: ${DB_USERNAME:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5437}/${DB_NAME:realworldapp}?connectTimeout=5000&amp;socketTimeout=30000
    hikari:
      maximum-pool-size: 5
      pool-name: pool
  jpa:
    properties:
      hibernate:
        format_sql: true


image:
  default:
    url: http://localhost:${server.port}/default.jpg
